
title: Truong Tan Dat
logo: ./picture/pic.png
description: I am pursing Engineer degree in Software Engineer at Sai Gon University.

Passionate about DevOps, I aim to streamline software development through automation and collaboration. Skilled in cloud infrastructure, Docker, Kubernetes, and Ansible, I'm committed to optimizing workflows 
for enhanced efficiency and scalability. Eager to contribute to dynamic teams and drive innovation in fast-paced environments.
